### ISSUE TITLE
Playing 'My Supermix' crashes after 2 or 3 songs

### ISSUE THREAD

**Issue by Habitual-Sinner** [Goldenfreddy0703/plugin.audio.ytmusic.exp#31] opened 2023-12-03 17:54 UTC
Hey, As per title, my supermix crashes kodi after playing 2 or 3 songs.

I'll post logs when it does it again.

I know that you've been looking for help maintaining the addon, I'm by no means a dev but have worked in IT for nearly 20 years and I'd be happy to try and lend a hand if I can.

**Comment by fischcode** [comment] 2023-12-04 22:00
Hi
I haven't had problems with the addon crashing Kodi so far: What is contained in 'My Supermix'? What version of Kodi are you using?

**Comment by Habitual-Sinner** [comment] 2023-12-05 08:43
Hi,
My Supermix is basically a YouTube curated playlist that spans all of your tastes.

It could possibly have something to do with crossfading enabled for songs not on the same album in Kodi.
I'll test it some more later and post logs.

Kodi 20.2 Linux, YTmusic Beta19 (I'll test on beta 20 that you just released)

**Comment by Habitual-Sinner** [comment] 2023-12-05 19:13
I've had a chance to test with the latest version and it plays fine with cross-fading disabled but still crashes Kodi with it enabled.
I've attached a debug log but it doesn't really show much
[Kodi crash with crossfading.txt](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/files/13570833/Kodi.crash.with.crossfading.txt)
.

**Comment by fischcode** [comment] 2023-12-05 21:41
Thank you very much for the clarification. I can easily think of ways how crossfading could interfere with the functioning of the addon. Unfortunately I am unable to reproduce the issue with Kodi 20.2 on Windows - while a 10 s setting for crossfading (with songs on the same album enabled) has a distinct effect when playing music from a file source, the setting seems to have no effect whatsoever when playing songs, albums or playlists with the ytmusic.exp addon (still have to test on LibreElec): What are the exact crossfading settings you are using? Do you get a crossfade effect when playing the first few songs of your playlist before Kodi crashes?

**Comment by fischcode** [comment] 2024-01-08 20:26
I am very sorry but I am still unable to reproduce your problem. Having found out that I need to select audio instead of video streams for crossfading to work with the ytmusic addon, various playlists play fine with crossfading enabled, both on Windows and with Kodi 20.2 on Linux Mint 21.2 Cinnamon: Is there anything special about the songs in your playlist (e.g. a very short song or the like)?

**Comment by Habitual-Sinner** [comment] 2024-01-11 05:28
Hey mate,

Travelling at the moment so unable to test further.

I'm sorry that I didn't specify that I had YTmusic set to audio in order
for crossfading to work, I'll be back home tomorrow so can provide more
information then.

**Comment by fischcode** [comment] 2024-08-29 20:17
Issue closed as I have been able to run YTMusic.exp with audio only and crossfading enabled for a long time without any problems: Could it be that the issue is related to a particular playlist? If so, try to create a public playlist with the same behaviour or provide a list of songs which can be used to create a playlist which is affected by the issue.

**Closed by fischcode** 2024-08-29 20:17 UTC
