### ISSUE TITLE
Same error multiple times

### ISSUE THREAD

**Issue by joaosagrath** [Goldenfreddy0703/plugin.audio.ytmusic.exp#30] opened 2023-11-22 03:10 UTC
Hello! this error is showed multiple times when open each folder from addon.
the music plays normally. but the notification are showing every time the library is loaded. 

https://pastebin.com/raw/Lgk34RHE

**Comment by fischcode** [comment] 2023-12-04 21:54
Hi
This looks like a song in one of your playlists doesn't behave as expected by the code: 
There might be a chance this behaviour is fixed with the latest release, beta20.
If not, can you see if one of your playlists is missing or truncated ? Knowing what playlists / songs are missing might allow me to reproduce the issue.

**Comment by joaosagrath** [comment] 2023-12-06 15:21
[kodi.log](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/files/13587864/kodi.log)

Here!!! jut open kodi and the error pops

**Comment by fischcode** [comment] 2023-12-06 21:38
Hi
Since I don't get the error, I would like you to try and replace D:\Kodi\Matrix\portable_data\addons\plugin.audio.ytmusic.exp\resources\lib\storage.py with the file contained in [storage.zip](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/files/13591838/storage.zip) after making sure that you are using the latest release, beta20
If this helps, I'll put the modification into the next release.
And if you could upload your library db file, located somewhere like D:\Kodi\Matrix\portable_data\userdata\addon_data\plugin.audio.ytmusic.exp\gpmusic.db, I might have a chance to understand better the underlying cause of the error. Thanks a lot in advance!

**Comment by fischcode** [comment] 2023-12-16 20:48
Issue was caused by automatically generated recap playlists which do not have a SetVideoId for their songs. Fixed in [beta21](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/releases/tag/1.0-beta21).

**Closed by fischcode** 2023-12-16 20:48 UTC
