### ISSUE TITLE
Again, quick and dirty search fix

### ISSUE THREAD

**Issue by weekendsource** [Goldenfreddy0703/plugin.audio.ytmusic.exp#34] opened 2024-01-14 18:36 UTC
In some cases search throws error:

> 2024-01-14 18:36:34.856 T:2224    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'KeyError'>
>                                                    Error Contents: 'browseId'
>                                                    Traceback (most recent call last):
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\addon.py", line 87, in <module>
>                                                        Navigation().listMenu(params)
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\navigation.py", line 111, in listMenu
>                                                        listItems, content = self.getSearch(keyboard.getText())
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\navigation.py", line 374, in getSearch
>                                                        listItems.extend(self.createPlaylistFolders(result['playlists']))
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\navigation.py", line 230, in createPlaylistFolders
>                                                        cm = self.getPlaylistContextMenu(playlist)
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\navigation.py", line 312, in getPlaylistContextMenu
>                                                        params = {'playlist_id': playlist.playlist_id, 'title': playlist.playlist_name}
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\wrapper.py", line 327, in playlist_id
>                                                        return self._item['browseId']
>                                                    KeyError: 'browseId'
>                                                    -->End of Python script error report<--

because some of the resulting playlists is missing browseId (playlist_id) and looks like this:

> {'category': 'Top result',
>  'resultType': 'playlist',
>  'thumbnails': [{'height': 225,
>                  'url': 'https://i.ytimg.com/vi/Fp1_y0jsfyA/sddefault.jpg?sqp=redacted_by_me_0',
>                  'width': 400},
>                 {'height': 450,
>                  'url': 'https://i.ytimg.com/vi/Fp1_y0jsfyA/hq720.jpg?sqp=redacted_by_me_1',
>                  'width': 800},
>                 {'height': 480,
>                  'url': 'https://i.ytimg.com/vi/Fp1_y0jsfyA/hq720.jpg?sqp=redacted_by_me_2',
>                  'width': 853}]}

I fixed it by changing createPlaylistFolders method (defined in line 226) in [navigation.py](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/blob/main/resources/lib/navigation.py) (adding test for browseId) from:

```
    def createPlaylistFolders(self, playlists):
        listItems = []
        for playlist in playlists:
            cm = self.getPlaylistContextMenu(playlist)
            folder = self.createFolder(playlist.playlist_name, {'path': "playlist", 'playlist_id': playlist.playlist_id}, cm, playlist.thumbnail)
            folder[1].setInfo(type='Music', infoLabels={
                                  'comment': playlist.description, 'mediatype': 'music'})
            listItems.append(folder)
        return listItems

```

to
deleted, see [the following coment](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/issues/34#issuecomment-1891063725)

**Comment by Goldenfreddy0703** [comment] 2024-01-14 19:11
Ohhh @fischcode this could maybe fix the search error thats happening, thank you @weekendsource

**Comment by weekendsource** [comment] 2024-01-14 19:19
@Goldenfreddy0703 @fischcode Unfortunately I just find out that this fix broke yt library playlists, so this issue is not resolved. Please ignore the fix part.

**Comment by Goldenfreddy0703** [comment] 2024-01-14 19:22
Awww it's ok @weekendsource , we hope to find a fix soon. Thank you tho

**Comment by weekendsource** [comment] 2024-01-14 19:28
Mea culpa :smile:

**Comment by weekendsource** [comment] 2024-01-14 20:27
@Goldenfreddy0703 @fischcode Well, it looks like this done it:

createPlaylistFolders method (defined in line 226) in [navigation.py](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/blob/main/resources/lib/navigation.py) with added test, changed from:

```
    def createPlaylistFolders(self, playlists):
        listItems = []
        for playlist in playlists:
            cm = self.getPlaylistContextMenu(playlist)
            folder = self.createFolder(playlist.playlist_name, {'path': "playlist", 'playlist_id': playlist.playlist_id}, cm, playlist.thumbnail)
            folder[1].setInfo(type='Music', infoLabels={
                                  'comment': playlist.description, 'mediatype': 'music'})
            listItems.append(folder)
        return listItems
```
to
```
    def createPlaylistFolders(self, playlists):
        listItems = []
        for playlist in playlists:
            if type (playlist._item) is dict and not 'browseId' in playlist._item:
                continue
            cm = self.getPlaylistContextMenu(playlist)
            folder = self.createFolder(playlist.playlist_name, {'path': "playlist", 'playlist_id': playlist.playlist_id}, cm, playlist.thumbnail)
            folder[1].setInfo(type='Music', infoLabels={
                                  'comment': playlist.description, 'mediatype': 'music'})
            listItems.append(folder)
        return listItems
```

It's a dirty solution but I have no doubt that @fishcode will make it pretty :smile:

**Comment by fischcode** [comment] 2024-01-14 21:17
@Goldenfreddy0703 @weekendsource 
As there is no way to open a playlist without a browseId, I have added code to skip those playlists directly in the wrapper class handling playlists from search results: [wrapper.py](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/blob/main/resources/lib/wrapper.py), Please let me know if this works for you.
(This modification should do exactly the same as the fix proposed by @Goldenfreddy0703 , but without breaking the encapsulation)

**Comment by weekendsource** [comment] 2024-01-14 21:39
@fischcode @Goldenfreddy0703 I tried new [wrapper.py](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/blob/main/resources/lib/wrapper.py) Unfortunately

> 2024-01-14 22:25:19.970 T:16124   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'KeyError'>
>                                                    Error Contents: 'browseId'
>                                                    Traceback (most recent call last):
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\addon.py", line 87, in <module>
>                                                        Navigation().listMenu(params)
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\navigation.py", line 121, in listMenu
>                                                        listItems, content = self.getSearch(get("query"))
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\navigation.py", line 375, in getSearch
>                                                        listItems.extend(self.createPlaylistFolders(result['playlists']))
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\navigation.py", line 232, in createPlaylistFolders
>                                                        cm = self.getPlaylistContextMenu(playlist)
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\navigation.py", line 314, in getPlaylistContextMenu
>                                                        params = {'playlist_id': playlist.playlist_id, 'title': playlist.playlist_name}
>                                                      File "C:\Users\weekendsource\AppData\Roaming\Kodi\addons\plugin.audio.ytmusic.exp\resources\lib\wrapper.py", line 335, in playlist_id
>                                                        return self._item['browseId']
>                                                    KeyError: 'browseId'
>                                                    -->End of Python script error report<--

Third one is a charm, previous fix broke moods&genres. This one does it for me:

```
    def createPlaylistFolders(self, playlists):
        listItems = []
        for playlist in playlists:
            if type(playlist._item) is dict and 'category' in playlist._item:
                continue
            cm = self.getPlaylistContextMenu(playlist)
            folder = self.createFolder(playlist.playlist_name, {'path': "playlist", 'playlist_id': playlist.playlist_id}, cm, playlist.thumbnail)
            folder[1].setInfo(type='Music', infoLabels={
                                  'comment': playlist.description, 'mediatype': 'music'})
            listItems.append(folder)
        return listItems
```

**Comment by fischcode** [comment] 2024-01-14 22:46
In the meantime, I found a way to reproduce the issue in the debugger using the playlist JSON provided by @weekendsource. As the approach with a modified wrapper didn't work (haven't quite figured out why), I've added a check on step further upstream and committed a modified api.py which works for me. As a nice side effect, playlists lacking browseId are written to the KODI log.

**Comment by weekendsource** [comment] 2024-01-14 23:06
@fischcode Everything works now, thank you :smiley:

**Comment by Goldenfreddy0703** [comment] 2024-01-15 01:05
Same here, thank you

**Closed** 2024-01-15 01:06 UTC
